version: "3.8"
services:
  client:
    container_name: modern-hackernews-client
    image: modern-hackernews-client
    stdin_open: true
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./:/app:delegated"
      - /app/node_modules/
